"use client";

import React from "react";
import useSWR from "swr";
import AccessGate from "@/components/AccessGate";
import ModulePageFrame from "@/components/enterprise/ModulePageFrame";
import Toast from "@/components/Toast";
import { UI } from "@/lib/ui";
import { dashboardFetcher } from "@/lib/swrFetcher";
import { apiFetchJson } from "@/lib/apiClient";

type PayrollRun = {
  id: number;
  month: number;
  year: number;
  status: "draft" | "generated" | "approved";
  generated_by_name?: string;
  approved_by_name?: string;
  generated_at?: string | null;
  approved_at?: string | null;
  notes?: string | null;
};

export default function PayrollControlPage() {
  const today = React.useMemo(() => new Date(), []);
  const [month, setMonth] = React.useState(String(today.getMonth() + 1));
  const [year, setYear] = React.useState(String(today.getFullYear()));
  const [notes, setNotes] = React.useState("");
  const [busy, setBusy] = React.useState(false);
  const [toast, setToast] = React.useState<{ message: string; variant: "success" | "error" | "blocked" } | null>(null);

  const runsSwr = useSWR<{ runs: PayrollRun[] }>("/api/hrms/payroll", dashboardFetcher, { revalidateOnFocus: false });

  async function generateRun() {
    setBusy(true);
    try {
      await apiFetchJson("/api/hrms/payroll", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          month: Number(month),
          year: Number(year),
          status: "generated",
          notes: notes || null,
        }),
      });
      setToast({ message: "Payroll run generated.", variant: "success" });
      await runsSwr.mutate();
    } catch (error) {
      setToast({ message: error instanceof Error ? error.message : "Failed to generate run.", variant: "error" });
    } finally {
      setBusy(false);
    }
  }

  async function approveRun(id: number) {
    setBusy(true);
    try {
      await apiFetchJson("/api/hrms/payroll", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id, action: "approve" }),
      });
      setToast({ message: "Payroll run approved.", variant: "success" });
      await runsSwr.mutate();
    } catch (error) {
      setToast({ message: error instanceof Error ? error.message : "Failed to approve run.", variant: "error" });
    } finally {
      setBusy(false);
    }
  }

  return (
    <AccessGate permissionKey="payroll.run">
      {toast ? <Toast message={toast.message} variant={toast.variant} onClose={() => setToast(null)} autoHideMs={1800} /> : null}
      <ModulePageFrame title="Payroll Control" subtitle="Generate payroll runs, approve payroll cycles, and export HRMS payroll reports.">
        <section className={UI.card + " p-4 sm:p-5"}>
          <h2 className="text-base font-semibold text-[var(--ats-text)]">Monthly payroll generation</h2>
          <div className="mt-3 grid gap-3 md:grid-cols-4">
            <select className={UI.select} value={month} onChange={(e) => setMonth(e.target.value)}>
              {Array.from({ length: 12 }, (_, index) => (
                <option key={index + 1} value={String(index + 1)}>
                  {new Date(2000, index, 1).toLocaleString("en-IN", { month: "long" })}
                </option>
              ))}
            </select>
            <input className={UI.input} type="number" value={year} onChange={(e) => setYear(e.target.value)} />
            <input className={UI.input} value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Notes (optional)" />
            <button type="button" className={UI.primaryButton + " py-2 text-sm"} onClick={() => void generateRun()} disabled={busy}>
              Generate run
            </button>
          </div>
          <div className="mt-3">
            <a className={UI.secondaryButton + " py-2 text-sm"} href="/api/hrms/payroll?format=csv">
              Export payroll CSV
            </a>
          </div>
        </section>

        <section className={UI.card + " mt-4 p-4 sm:p-5"}>
          <h2 className="text-base font-semibold text-[var(--ats-text)]">Payroll runs</h2>
          <div className="mt-3 overflow-x-auto">
            <table className="min-w-full text-sm">
              <thead>
                <tr className="text-left text-[var(--ats-text-muted)]">
                  <th className="px-2 py-2">Month</th>
                  <th className="px-2 py-2">Status</th>
                  <th className="px-2 py-2">Generated by</th>
                  <th className="px-2 py-2">Approved by</th>
                  <th className="px-2 py-2">Action</th>
                </tr>
              </thead>
              <tbody>
                {(runsSwr.data?.runs || []).map((run) => (
                  <tr key={run.id} className="border-t border-[var(--ats-border)]">
                    <td className="px-2 py-2">
                      {new Date(Date.UTC(run.year, run.month - 1, 1)).toLocaleString("en-IN", { month: "short", year: "numeric" })}
                    </td>
                    <td className="px-2 py-2 capitalize">{run.status}</td>
                    <td className="px-2 py-2">{run.generated_by_name || "-"}</td>
                    <td className="px-2 py-2">{run.approved_by_name || "-"}</td>
                    <td className="px-2 py-2">
                      {run.status !== "approved" ? (
                        <button type="button" className={UI.secondaryButton + " py-1.5 text-xs"} onClick={() => void approveRun(run.id)} disabled={busy}>
                          Approve
                        </button>
                      ) : (
                        "-"
                      )}
                    </td>
                  </tr>
                ))}
                {(runsSwr.data?.runs || []).length === 0 ? (
                  <tr>
                    <td colSpan={5} className="px-2 py-4 text-center text-[var(--ats-text-muted)]">
                      No payroll runs yet.
                    </td>
                  </tr>
                ) : null}
              </tbody>
            </table>
          </div>
        </section>
      </ModulePageFrame>
    </AccessGate>
  );
}
