"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback,useEffect,useState } from "react";
import { ArrowDown,ArrowUp,Copy,Mail,RefreshCw,Save,ShieldCheck,Trash2 } from "lucide-react";

type Question={id?:number;order_number?:number;question_text:string;skill_name:string;difficulty:"BEGINNER"|"INTERMEDIATE"|"ADVANCED";expected_points_json:string[];scoring_rubric_json:Array<{criterion:string;weight:number}>;max_score:number};
export default function AiInterviewDetail({id}:{id:number}){
 const router=useRouter();
 const [data,setData]=useState<any>(null);const [questions,setQuestions]=useState<Question[]>([]);const [link,setLink]=useState("");const [busy,setBusy]=useState("");const [message,setMessage]=useState("");const [error,setError]=useState("");
 const load=useCallback(async()=>{const r=await fetch(`/api/ai-interviews/${id}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Failed to load");setData(d);setQuestions(d.questions||[]);},[id]);
 useEffect(()=>{setLink(sessionStorage.getItem(`ai-interview-link:${id}`)||"");void load().catch(e=>setError(e.message));},[id,load]);
 async function action(name:string,url:string,options:RequestInit={method:"POST"}){setBusy(name);setError("");setMessage("");try{const r=await fetch(url,options);const d=await r.json();if(!r.ok)throw new Error(d.error||"Action failed");if(d.public_url){setLink(d.public_url);sessionStorage.setItem(`ai-interview-link:${id}`,d.public_url);}setMessage(name==="send"?"Invitation sent successfully.":"Interview updated successfully.");await load();}catch(e){setError(e instanceof Error?e.message:"Action failed");}finally{setBusy("");}}
 async function saveQuestions(){const payload=questions.map(q=>({question:q.question_text,skill:q.skill_name||"General",difficulty:q.difficulty,expectedPoints:q.expected_points_json?.length?q.expected_points_json:["Relevant and accurate explanation"],scoringRubric:q.scoring_rubric_json?.length?q.scoring_rubric_json:[{criterion:"Accuracy and relevance",weight:100}],maxScore:Number(q.max_score||10)}));await action("save",`/api/ai-interviews/${id}/questions`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({questions:payload})});}
 async function deleteInterview(){if(!window.confirm("Permanently delete this AI interview, its report, recording, and snapshot? This cannot be undone."))return;setBusy("delete");setError("");try{const r=await fetch(`/api/ai-interviews/${id}/delete`,{method:"DELETE"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Interview could not be deleted");router.push("/ai-interviews");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Interview could not be deleted");setBusy("");}}
 function update(index:number,patch:Partial<Question>){setQuestions(prev=>prev.map((q,i)=>i===index?{...q,...patch}:q));}
 function move(index:number,direction:-1|1){setQuestions(prev=>{const target=index+direction;if(target<0||target>=prev.length)return prev;const next=[...prev];[next[index],next[target]]=[next[target],next[index]];return next;});}
 if(!data)return <div className="rounded-2xl border border-slate-200 bg-white p-10 text-center text-slate-500">{error||"Loading AI interview..."}</div>;
 const interview=data.interview;const editable=interview.status==="DRAFT";
 return <div className="space-y-5">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><Link href="/ai-interviews" className="text-sm font-semibold text-blue-700">AI Interviews</Link><h1 className="mt-1 text-2xl font-bold text-slate-950">{interview.title}</h1><p className="text-sm text-slate-600">{interview.candidate_name} · {interview.job_title}</p></div><div className="flex flex-wrap gap-2">{interview.status==="COMPLETED"&&<Link href={`/ai-interviews/${id}/report`} className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white">Open report</Link>}{data.capabilities?.can_delete&&<button disabled={!!busy} onClick={()=>void deleteInterview()} className="inline-flex items-center gap-2 rounded-xl border border-rose-200 bg-white px-4 py-2 text-sm font-semibold text-rose-700 disabled:opacity-50"><Trash2 className="h-4 w-4"/>{busy==="delete"?"Deleting...":"Delete"}</button>}<Link href="/ai-interviews/settings" className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700">Settings</Link></div></div>
  {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}{message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{message}</div>}
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Status",interview.status],["Questions",questions.length],["Duration",`${interview.duration_minutes} min`],["Evaluation",interview.evaluation_status],["Recording",interview.video_status]].map(([label,value])=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</div><div className="mt-1 font-bold text-slate-900">{value}</div></div>)}</section>
  {link&&<section className="rounded-2xl border border-blue-200 bg-blue-50 p-4"><div className="flex items-center gap-2 font-bold text-blue-950"><ShieldCheck className="h-5 w-5"/>Secure candidate link</div><div className="mt-2 flex flex-col gap-2 sm:flex-row"><input readOnly value={link} className="min-w-0 flex-1 rounded-xl border border-blue-200 bg-white px-3 py-2 text-sm"/><button onClick={()=>void navigator.clipboard.writeText(link).then(()=>setMessage("Link copied."))} className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-4 py-2 text-sm font-semibold text-blue-700 ring-1 ring-blue-200"><Copy className="h-4 w-4"/>Copy</button></div><p className="mt-2 text-xs text-blue-700">Generating or sending a new link revokes this link.</p></section>}
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold text-slate-950">Interview questions</h2><p className="text-sm text-slate-500">Review every AI-generated question before activation.</p></div>{editable&&<div className="flex gap-2"><button disabled={!!busy} onClick={()=>void action("regenerate",`/api/ai-interviews/${id}/questions`)} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold"><RefreshCw className="h-4 w-4"/>Regenerate</button><button disabled={!!busy} onClick={()=>void saveQuestions()} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-3 py-2 text-sm font-semibold text-white"><Save className="h-4 w-4"/>Save questions</button></div>}</div>
   <div className="mt-4 space-y-3">{questions.map((q,index)=><article key={q.id||index} className="rounded-xl border border-slate-200 p-4"><div className="mb-2 flex items-center justify-between gap-2"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-blue-700">Question {index+1}<span className="rounded-full bg-slate-100 px-2 py-0.5 text-slate-600">{q.difficulty}</span></div>{editable&&<div className="flex gap-1"><button aria-label="Move question up" disabled={index===0} onClick={()=>move(index,-1)} className="rounded-lg border border-slate-200 p-1.5 disabled:opacity-30"><ArrowUp className="h-4 w-4"/></button><button aria-label="Move question down" disabled={index===questions.length-1} onClick={()=>move(index,1)} className="rounded-lg border border-slate-200 p-1.5 disabled:opacity-30"><ArrowDown className="h-4 w-4"/></button><button aria-label="Delete question" disabled={questions.length<=1} onClick={()=>setQuestions(prev=>prev.filter((_,i)=>i!==index))} className="rounded-lg border border-rose-200 p-1.5 text-rose-600 disabled:opacity-30"><Trash2 className="h-4 w-4"/></button></div>}</div><textarea disabled={!editable} rows={3} value={q.question_text} onChange={e=>update(index,{question_text:e.target.value})} className="w-full rounded-xl border border-slate-200 p-3 text-sm disabled:bg-slate-50"/><div className="mt-2 grid gap-2 sm:grid-cols-2"><input disabled={!editable} value={q.skill_name||""} onChange={e=>update(index,{skill_name:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2 text-sm" placeholder="Skill"/><input disabled={!editable} value={(q.expected_points_json||[]).join("; ")} onChange={e=>update(index,{expected_points_json:e.target.value.split(";").map(x=>x.trim()).filter(Boolean)})} className="rounded-xl border border-slate-200 px-3 py-2 text-sm" placeholder="Expected points separated by ;"/></div></article>)}</div>
  </section>
  <div className="flex flex-wrap justify-end gap-2">{['FAILED','PROCESSING'].includes(interview.status)&&interview.evaluation_status!=="COMPLETED"&&<button disabled={!!busy} onClick={()=>void action("retry",`/api/ai-interviews/${id}/retry`)} className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-2 text-sm font-bold text-amber-800">{busy==="retry"?"Starting evaluation...":interview.status==="FAILED"?"Retry evaluation":"Process evaluation now"}</button>}{editable&&<button disabled={!!busy} onClick={()=>void action("activate",`/api/ai-interviews/${id}/activate`)} className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-2 text-sm font-bold text-blue-800">Activate and generate link</button>} {!['COMPLETED','CANCELLED','EXPIRED','PROCESSING','FAILED'].includes(interview.status)&&<><button disabled={!!busy} onClick={()=>void action("cancel",`/api/ai-interviews/${id}`,{method:"DELETE"})} className="rounded-xl border border-rose-200 px-4 py-2 text-sm font-bold text-rose-700">Cancel</button><button disabled={!!busy} onClick={()=>void action("send",`/api/ai-interviews/${id}/send`)} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-2 text-sm font-bold text-white"><Mail className="h-4 w-4"/>Send invitation</button></>}</div>
 </div>;
}
