"use client";

/* eslint-disable @next/next/no-img-element -- authenticated snapshots cannot use the public image optimizer */

import Link from "next/link";
import { useEffect,useRef,useState } from "react";
import { Download } from "lucide-react";

export default function AiInterviewReport({id}:{id:number}){
 const [data,setData]=useState<any>(null);const [error,setError]=useState("");const [decision,setDecision]=useState("");const [comments,setComments]=useState("");
 const videoRef=useRef<HTMLVideoElement|null>(null);
 useEffect(()=>{void fetch(`/api/ai-interviews/${id}/report`,{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setDecision(d.interview.recruiter_decision||"");setComments(d.interview.recruiter_comments||"");}).catch(e=>setError(e.message));},[id]);
 async function save(){const r=await fetch(`/api/ai-interviews/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({recruiter_decision:decision,recruiter_comments:comments})});if(!r.ok)setError((await r.json()).error||"Could not save decision");}
 if(!data)return <div className="p-8 text-center text-slate-500">{error||"Loading report..."}</div>;
 const i=data.interview,e=data.evaluation;
 return <div className="space-y-5 print:p-0"><div className="flex flex-wrap justify-between gap-3"><div><Link href={`/ai-interviews/${id}`} className="text-sm font-semibold text-blue-700">Interview details</Link><h1 className="mt-1 text-2xl font-bold text-slate-950">AI Interview Report</h1></div><button onClick={()=>window.print()} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold print:hidden">Print report</button></div>
 <section className="grid gap-5 rounded-2xl border border-slate-200 bg-white p-5 md:grid-cols-[1fr_220px]"><div><h2 className="text-2xl font-bold text-slate-950">{i.candidate_name}</h2><div className="mt-3 space-y-1 text-sm text-slate-700"><p><strong>Role:</strong> {i.job_title}</p><p><strong>Email:</strong> {i.candidate_email||"Not available"}</p><p><strong>Phone:</strong> {i.candidate_phone||"Not available"}</p><p><strong>Experience range:</strong> {i.experience_requirement||"Not specified"}</p><p><strong>Interview started:</strong> {i.started_at?new Date(i.started_at).toLocaleString("en-IN",{timeZone:"Asia/Kolkata"}):"Not available"}</p><p><strong>Interview ended:</strong> {i.completed_at?new Date(i.completed_at).toLocaleString("en-IN",{timeZone:"Asia/Kolkata"}):"Not available"}</p></div>{i.video_status==="UPLOADED"&&<a href={`/api/ai-interviews/${id}/recording`} className="mt-3 inline-block text-sm font-semibold text-blue-700">Open recording</a>}</div>{i.snapshot_status==="CAPTURED"?<div><img src={`/api/ai-interviews/${id}/snapshot`} alt={`${i.candidate_name} during AI interview`} className="aspect-[4/3] w-full rounded-xl border border-slate-200 object-cover"/><a href={`/api/ai-interviews/${id}/snapshot?download=1`} className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-700 print:hidden"><Download className="h-4 w-4"/>Download image</a></div>:<div className="flex min-h-40 items-center justify-center rounded-xl bg-slate-100 p-4 text-center text-sm text-slate-500">No candidate snapshot was captured.</div>}</section>
 <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Overall",i.overall_score==null?"—":`${Math.round(i.overall_score)}%`],["Technical",i.technical_score==null?"—":`${Math.round(i.technical_score)}%`],["Communication",i.communication_score==null?"—":`${Math.round(i.communication_score)}%`],["Experience relevance",i.experience_relevance_score==null?"—":`${Math.round(i.experience_relevance_score)}%`]].map(([l,v])=><div key={l} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="text-xs font-semibold uppercase text-slate-500">{l}</div><div className="mt-1 text-2xl font-bold text-slate-950">{v}</div></div>)}</section>
 <section className="grid gap-4 lg:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5 lg:col-span-2"><h2 className="font-bold">Evaluation</h2><p className="mt-2 text-sm leading-6 text-slate-700">{e?.summary||"Evaluation is still processing."}</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><h3 className="text-sm font-bold text-emerald-700">Strengths</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-700">{(e?.strengths_json||[]).map((x:string)=><li key={x}>{x}</li>)}</ul></div><div><h3 className="text-sm font-bold text-amber-700">Concerns</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-700">{(e?.concerns_json||[]).map((x:string)=><li key={x}>{x}</li>)}</ul></div></div></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Integrity</h2><div className="mt-2 text-xl font-bold text-slate-950">{i.integrity_risk||"Not assessed"}</div><p className="mt-2 text-xs text-slate-500">Integrity signals are approximate and do not change the performance score.</p><div className="mt-3 space-y-1 text-sm">{Object.entries(data.integrity_counts||{}).map(([k,v])=><div key={k} className="flex justify-between"><span>{k.replaceAll("_"," ")}</span><strong>{String(v)}</strong></div>)}</div></div></section>
 <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Question-level review</h2><div className="mt-4 space-y-4">{data.answers.map((a:any)=><article key={a.order_number} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><div className="font-bold text-slate-900">{a.order_number}. {a.question_text}</div><div className="font-bold text-blue-700">{a.score==null?"—":`${a.score}/${a.max_score}`}</div></div><div className="mt-2 text-xs font-semibold uppercase text-slate-500">{a.skill_name} · {a.difficulty}</div><p className="mt-3 whitespace-pre-wrap rounded-lg bg-slate-50 p-3 text-sm text-slate-700">{a.transcript||"No answer submitted."}</p>{a.evaluator_feedback&&<p className="mt-2 text-sm text-slate-600">{a.evaluator_feedback}</p>}</article>)}</div></section>
 {data.events?.length>0&&<section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Integrity timeline</h2><div className="mt-3 max-h-80 space-y-2 overflow-y-auto">{data.events.map((event:any,index:number)=><button key={`${event.occurred_at}-${index}`} onClick={()=>{if(videoRef.current&&event.evidence_timestamp_seconds!=null){videoRef.current.currentTime=Number(event.evidence_timestamp_seconds);void videoRef.current.play();}}} className="flex w-full items-start justify-between gap-3 rounded-xl border border-slate-100 p-3 text-left hover:bg-slate-50"><span><strong className="text-sm text-slate-900">{event.event_type.replaceAll("_"," ")}</strong><span className="mt-1 block text-xs text-slate-500">{new Date(event.occurred_at).toLocaleString("en-IN")}{event.duration_seconds?` · ${Number(event.duration_seconds).toFixed(1)} sec`:""}</span></span><span className="text-xs font-semibold text-amber-700">{event.severity}</span></button>)}</div></section>}
 {i.video_status==="UPLOADED"&&<section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Recording</h2><video ref={videoRef} controls className="mt-3 max-h-[520px] w-full rounded-xl bg-black" src={`/api/ai-interviews/${id}/recording`}/></section>}
 {i.video_status==="DELETED_BY_RETENTION"&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Recording removed according to retention policy. Transcript and integrity event data remain available.</div>}
 <section className="rounded-2xl border border-slate-200 bg-white p-5 print:hidden"><h2 className="font-bold">Recruiter decision</h2><div className="mt-3 grid gap-3 md:grid-cols-3"><select value={decision} onChange={e=>setDecision(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2"><option value="">Select decision</option><option value="PROCEED">Proceed</option><option value="HOLD">Hold</option><option value="REJECT">Reject</option><option value="SCHEDULE_HUMAN_INTERVIEW">Schedule human interview</option></select><textarea value={comments} onChange={e=>setComments(e.target.value)} className="rounded-xl border border-slate-200 p-3 md:col-span-2" placeholder="Recruiter comments"/></div><button onClick={()=>void save()} className="mt-3 rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white">Save decision</button></section>
 </div>;
}
