"use client";

import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";

type Option={id:number;title?:string;full_name?:string;email?:string};
export default function AiInterviewCreate(){
 const router=useRouter();const [jobs,setJobs]=useState<Option[]>([]);const [candidates,setCandidates]=useState<Option[]>([]);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
 const [form,setForm]=useState({job_id:"",candidate_id:"",title:"AI Interview",instructions:"Answer each question clearly using examples from your experience.",difficulty:"MIXED",skills:"",question_count:7,duration_minutes:40,expires_at:"",recording_enabled:true,screen_share_enabled:false,fullscreen_required:true,face_monitoring_enabled:true,gaze_monitoring_enabled:true});
 useEffect(()=>{void Promise.all([fetch("/api/jobs").then(r=>r.json()),fetch("/api/candidates").then(r=>r.json())]).then(([j,c])=>{setJobs(Array.isArray(j)?j:(j.jobs||j.data||[]));setCandidates(Array.isArray(c)?c:(c.candidates||c.data||[]));});},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");try{const payload={...form,job_id:Number(form.job_id),candidate_id:Number(form.candidate_id),skills:form.skills.split(",").map(x=>x.trim()).filter(Boolean),expires_at:new Date(form.expires_at).toISOString()};const r=await fetch("/api/ai-interviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not create AI interview");if(d.public_url)sessionStorage.setItem(`ai-interview-link:${d.interview.id}`,d.public_url);router.push(`/ai-interviews/${d.interview.id}`);}catch(e){setError(e instanceof Error?e.message:"Could not create AI interview");setSaving(false);}}
 const input="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100";
 return <form onSubmit={submit} className="mx-auto max-w-5xl space-y-5"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-slate-950">Create AI Interview</h1><p className="mt-1 text-sm text-slate-600">Questions are generated from the selected job and candidate resume, then remain editable before activation.</p></div><Link href="/ai-interviews" className="text-sm font-semibold text-slate-600">Back</Link></div>
 {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
 <section className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-2">
  <label className="text-sm font-semibold text-slate-700">Job<select required value={form.job_id} onChange={e=>setForm({...form,job_id:e.target.value})} className={input}><option value="">Select job</option>{jobs.map(j=><option key={j.id} value={j.id}>{j.title}</option>)}</select></label>
  <label className="text-sm font-semibold text-slate-700">Candidate<select required value={form.candidate_id} onChange={e=>setForm({...form,candidate_id:e.target.value})} className={input}><option value="">Select candidate</option>{candidates.map(c=><option key={c.id} value={c.id}>{c.full_name} {c.email?`· ${c.email}`:""}</option>)}</select></label>
  <label className="text-sm font-semibold text-slate-700 md:col-span-2">Interview title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className={input}/></label>
  <label className="text-sm font-semibold text-slate-700">Difficulty<select value={form.difficulty} onChange={e=>setForm({...form,difficulty:e.target.value})} className={input}><option value="MIXED">Mixed</option><option value="BEGINNER">Beginner</option><option value="INTERMEDIATE">Intermediate</option><option value="ADVANCED">Advanced</option></select></label>
  <label className="text-sm font-semibold text-slate-700">Skills to evaluate<input value={form.skills} onChange={e=>setForm({...form,skills:e.target.value})} placeholder="Python, system design, AWS" className={input}/></label>
  <label className="text-sm font-semibold text-slate-700">Questions<input type="number" min={1} max={20} value={form.question_count} onChange={e=>setForm({...form,question_count:Number(e.target.value)})} className={input}/></label>
  <label className="text-sm font-semibold text-slate-700">Duration (minutes)<input type="number" min={5} max={180} value={form.duration_minutes} onChange={e=>setForm({...form,duration_minutes:Number(e.target.value)})} className={input}/></label>
  <label className="text-sm font-semibold text-slate-700">Link expiry<input required type="datetime-local" value={form.expires_at} onChange={e=>setForm({...form,expires_at:e.target.value})} className={input}/></label>
  <label className="text-sm font-semibold text-slate-700 md:col-span-2">Instructions<textarea rows={4} value={form.instructions} onChange={e=>setForm({...form,instructions:e.target.value})} className={input}/></label>
 </section>
 <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">Interview controls</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{([['recording_enabled','Record camera and mic'],['screen_share_enabled','Require screen share'],['fullscreen_required','Require fullscreen'],['face_monitoring_enabled','Face presence'],['gaze_monitoring_enabled','Approx. looking away']] as const).map(([key,label])=><label key={key} className="flex items-center gap-2 rounded-xl border border-slate-200 p-3 text-sm text-slate-700"><input type="checkbox" checked={form[key]} onChange={e=>setForm({...form,[key]:e.target.checked})}/>{label}</label>)}</div></section>
 <div className="flex justify-end"><button disabled={saving} className="rounded-xl bg-blue-600 px-6 py-3 text-sm font-bold text-white shadow-sm hover:bg-blue-700 disabled:opacity-50">{saving?"Creating and generating questions...":"Create and generate questions"}</button></div>
 </form>;
}
