"use client";

import { useCallback,useEffect,useRef,useState } from "react";
import { BrainCircuit,Camera,CheckCircle2,Clock,Mic,MonitorUp,ShieldCheck,Wifi } from "lucide-react";

type Interview={id:number;title:string;instructions:string;duration_minutes:number;candidate_name:string;job_title:string;status:string;recording_enabled:boolean;screen_share_enabled:boolean;fullscreen_required:boolean;camera_required:boolean;microphone_required:boolean;face_monitoring_enabled:boolean;gaze_monitoring_enabled:boolean;face_missing_threshold_seconds?:number;requirements?:Record<string,boolean>};
type Question={id:number;order_number:number;question_text:string;skill_name:string;difficulty:string};
type Step="loading"|"intro"|"system"|"interview"|"thanks"|"error";

declare global{interface Window{webkitSpeechRecognition?:new()=>any;SpeechRecognition?:new()=>any;}}

export default function CandidateAiInterviewRoom({secureToken}:{secureToken?:string}){
 const [step,setStep]=useState<Step>("loading");const [interview,setInterview]=useState<Interview|null>(null);const [questions,setQuestions]=useState<Question[]>([]);const [current,setCurrent]=useState(0);const [answer,setAnswer]=useState("");const [error,setError]=useState("");const [checking,setChecking]=useState(false);const [checks,setChecks]=useState<Record<string,boolean>>({});const [consent,setConsent]=useState(false);const [timeLeft,setTimeLeft]=useState(0);const [warning,setWarning]=useState("");const [recording,setRecording]=useState(false);const [speaking,setSpeaking]=useState(false);
 const mediaRef=useRef<MediaStream|null>(null);const screenRef=useRef<MediaStream|null>(null);const videoRef=useRef<HTMLVideoElement|null>(null);const recorderRef=useRef<MediaRecorder|null>(null);const uploadIdRef=useRef("");const chunkRef=useRef(0);const uploadChain=useRef<Promise<unknown>>(Promise.resolve());const startedAt=useRef(0);const questionStartedAt=useRef(0);const recognitionRef=useRef<any>(null);

 const loadState=useCallback(async()=>{const r=await fetch("/api/ai-interview/state",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load interview");setInterview(d.interview);setQuestions(d.questions||[]);setTimeLeft(Number(d.interview.duration_minutes)*60);setStep(d.consented?"system":"intro");},[]);
 useEffect(()=>{void(async()=>{try{if(secureToken){const r=await fetch("/api/ai-interview/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token:secureToken})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to open interview");window.history.replaceState({},"","/ai-interview/session");}await loadState();}catch(e){setError(e instanceof Error?e.message:"Unable to open interview");setStep("error");}})();},[secureToken,loadState]);

 const sendEvent=useCallback((event_type:string,metadata:Record<string,unknown>={})=>{void fetch("/api/ai-interview/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({event_type,occurred_at:new Date().toISOString(),evidence_timestamp_seconds:startedAt.current?Math.round((Date.now()-startedAt.current)/1000):0,question_id:questions[current]?.id||null,metadata})}).catch(()=>{});},[questions,current]);
 useEffect(()=>{if(step!=="interview")return;const hidden=()=>{if(document.hidden){sendEvent("TAB_HIDDEN");setWarning("Please keep the interview tab visible.");}};const blur=()=>sendEvent("WINDOW_BLUR");const fullscreen=()=>{if(interview?.fullscreen_required&&!document.fullscreenElement){sendEvent("FULLSCREEN_EXIT");setWarning("Please return to fullscreen mode.");}};const offline=()=>sendEvent("CONNECTION_LOST");const online=()=>sendEvent("CONNECTION_RESTORED");const copy=(e:ClipboardEvent)=>{e.preventDefault();sendEvent("COPY_ATTEMPT");};const paste=(e:ClipboardEvent)=>{e.preventDefault();sendEvent("PASTE_ATTEMPT");};document.addEventListener("visibilitychange",hidden);window.addEventListener("blur",blur);document.addEventListener("fullscreenchange",fullscreen);window.addEventListener("offline",offline);window.addEventListener("online",online);document.addEventListener("copy",copy);document.addEventListener("paste",paste);return()=>{document.removeEventListener("visibilitychange",hidden);window.removeEventListener("blur",blur);document.removeEventListener("fullscreenchange",fullscreen);window.removeEventListener("offline",offline);window.removeEventListener("online",online);document.removeEventListener("copy",copy);document.removeEventListener("paste",paste);};},[step,sendEvent,interview]);
 // Completion is intentionally bound to the active interview timer instance.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{if(step!=="interview")return;const timer=setInterval(()=>setTimeLeft(value=>{if(value<=1){clearInterval(timer);void finishInterview();return 0;}return value-1;}),1000);return()=>clearInterval(timer);},[step]);
 useEffect(()=>{if(step!=="interview")return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue="";};window.addEventListener("beforeunload",warn);const heartbeat=setInterval(()=>{void fetch("/api/ai-interview/heartbeat",{method:"POST"}).catch(()=>{});},15000);return()=>{window.removeEventListener("beforeunload",warn);clearInterval(heartbeat);};},[step]);
 useEffect(()=>{if(videoRef.current&&mediaRef.current){videoRef.current.srcObject=mediaRef.current;void videoRef.current.play().catch(()=>{});}},[step]);
 useEffect(()=>{
  if(step!=="interview"||!interview?.face_monitoring_enabled||!videoRef.current)return;
  let cancelled=false;let timer:ReturnType<typeof setInterval>|null=null;let detector:{detectForVideo:(video:HTMLVideoElement,time:number)=>{faceLandmarks?:Array<Array<{x:number;y:number;z?:number}>>};close:()=>void}|null=null;
  let noFaceSince=0,multipleSince=0,awaySince=0,lastAwayEvent=0,noFaceLogged=false,multipleLogged=false;
  void (async()=>{try{
    const vision=await import("@mediapipe/tasks-vision");
    const files=await vision.FilesetResolver.forVisionTasks("https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/wasm");
    detector=await vision.FaceLandmarker.createFromOptions(files,{baseOptions:{modelAssetPath:"https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task",delegate:"GPU"},runningMode:"VIDEO",numFaces:2,minFaceDetectionConfidence:.55,minTrackingConfidence:.55});
    timer=setInterval(()=>{const video=videoRef.current;if(cancelled||!video||video.readyState<2||!detector)return;const now=performance.now();const faces=detector.detectForVideo(video,now).faceLandmarks||[];
      if(faces.length===0){if(!noFaceSince)noFaceSince=Date.now();if(!noFaceLogged&&Date.now()-noFaceSince>Math.max(3,interview.face_missing_threshold_seconds||5)*1000){sendEvent("FACE_NOT_VISIBLE",{approximate:true});noFaceLogged=true;}}else{noFaceSince=0;noFaceLogged=false;}
      if(faces.length>1){if(!multipleSince)multipleSince=Date.now();if(!multipleLogged&&Date.now()-multipleSince>2000){sendEvent("MULTIPLE_FACES",{approximate:true});multipleLogged=true;}}else{multipleSince=0;multipleLogged=false;}
      if(faces.length===1&&interview.gaze_monitoring_enabled){const points=faces[0];const nose=points[1],left=points[33],right=points[263];if(nose&&left&&right){const eyeWidth=Math.max(.001,Math.abs(right.x-left.x));const offset=Math.abs(nose.x-(left.x+right.x)/2)/eyeWidth;const away=offset>.22;if(away){if(!awaySince)awaySince=Date.now();if(Date.now()-awaySince>2000&&Date.now()-lastAwayEvent>5000){sendEvent("LOOKING_AWAY",{approximate:true,head_offset:Number(offset.toFixed(2))});lastAwayEvent=Date.now();awaySince=0;}}else awaySince=0;}}
    },500);
  }catch(error){console.warn("Face monitoring unavailable",error);}})();
  return()=>{cancelled=true;if(timer)clearInterval(timer);detector?.close();};
 },[step,interview,sendEvent]);
 useEffect(()=>()=>{mediaRef.current?.getTracks().forEach(t=>t.stop());screenRef.current?.getTracks().forEach(t=>t.stop());recognitionRef.current?.stop?.();},[]);

 async function acceptConsent(){if(!consent)return;setChecking(true);setError("");try{const r=await fetch("/api/ai-interview/consent",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({camera_consent:true,microphone_consent:true,recording_consent:true,screen_share_consent:Boolean(interview?.screen_share_enabled),monitoring_consent:true})});const d=await r.json();if(!r.ok)throw new Error(d.error);setStep("system");}catch(e){setError(e instanceof Error?e.message:"Consent could not be saved");}finally{setChecking(false);}}
 async function runChecks(){setChecking(true);setError("");try{const browser=/Chrome|Edg/.test(navigator.userAgent);const stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});mediaRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play();}stream.getVideoTracks()[0]?.addEventListener("ended",()=>sendEvent("CAMERA_DISABLED"));stream.getAudioTracks()[0]?.addEventListener("ended",()=>sendEvent("MICROPHONE_DISABLED"));let screen=true;if(interview?.screen_share_enabled){screenRef.current=await navigator.mediaDevices.getDisplayMedia({video:true});screenRef.current.getVideoTracks()[0]?.addEventListener("ended",()=>sendEvent("SCREEN_SHARE_STOPPED"));}setChecks({browser,camera:stream.getVideoTracks().length>0,microphone:stream.getAudioTracks().length>0,network:navigator.onLine,screen});}catch(e){setError("Camera or microphone permission was denied. Allow access and retry the system check.");sendEvent("PERMISSION_DENIED",{message:e instanceof Error?e.message:"permission denied"});}finally{setChecking(false);}}
 function playSpeakerTest(){const Context=window.AudioContext||(window as any).webkitAudioContext;const ctx=new Context();const oscillator=ctx.createOscillator();const gain=ctx.createGain();gain.gain.value=.08;oscillator.connect(gain);gain.connect(ctx.destination);oscillator.start();oscillator.stop(ctx.currentTime+.35);setChecks(value=>({...value,speaker:true}));}
 async function beginInterview(){if(!Object.values(checks).every(Boolean)){setError("Complete all required system checks before starting.");return;}try{if(interview?.fullscreen_required&&!document.fullscreenElement)await document.documentElement.requestFullscreen();const r=await fetch("/api/ai-interview/start",{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.error);uploadIdRef.current=d.upload_id;startedAt.current=Date.now();setStep("interview");await beginQuestion(0);if(interview?.recording_enabled&&mediaRef.current)startRecording(mediaRef.current);sendEvent("INTERVIEW_STARTED");}catch(e){setError(e instanceof Error?e.message:"Interview could not start");}}
 function startRecording(stream:MediaStream){const mimeType=MediaRecorder.isTypeSupported("video/webm;codecs=vp9,opus")?"video/webm;codecs=vp9,opus":"video/webm";const recorder=new MediaRecorder(stream,{mimeType});recorderRef.current=recorder;chunkRef.current=0;recorder.ondataavailable=event=>{if(!event.data.size)return;const seq=chunkRef.current++;uploadChain.current=uploadChain.current.then(()=>fetch("/api/ai-interview/recording/chunk",{method:"POST",headers:{"Content-Type":"application/octet-stream","x-upload-id":uploadIdRef.current,"x-chunk-sequence":String(seq)},body:event.data}).then(async r=>{if(!r.ok)throw new Error((await r.json()).error||"Recording upload failed");})).catch(()=>{sendEvent("RECORDING_INTERRUPTED");});};recorder.start(5000);setRecording(true);}
 async function beginQuestion(index:number){setCurrent(index);setAnswer("");questionStartedAt.current=Date.now();const q=questions[index];if(q)await fetch("/api/ai-interview/answer",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"start",question_id:q.id,idempotency_key:`start-${q.id}`})});}
 function speakQuestion(){const q=questions[current];if(!q||!window.speechSynthesis)return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(q.question_text);utterance.onstart=()=>setSpeaking(true);utterance.onend=()=>setSpeaking(false);window.speechSynthesis.speak(utterance);}
 function startDictation(){const Ctor=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Ctor){setError("Live speech transcription is unavailable in this browser. You can type your answer.");return;}const recognition=new Ctor();recognition.continuous=true;recognition.interimResults=true;recognition.lang="en-IN";recognition.onresult=(event:any)=>{let text="";for(let i=0;i<event.results.length;i++)text+=`${event.results[i][0].transcript} `;setAnswer(text.trim());};recognition.onerror=()=>setError("Speech transcription paused. You can continue by typing.");recognition.start();recognitionRef.current=recognition;}
 async function submitAnswer(){const q=questions[current];recognitionRef.current?.stop?.();const r=await fetch("/api/ai-interview/answer",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"complete",question_id:q.id,transcript:answer,duration_seconds:Math.round((Date.now()-questionStartedAt.current)/1000),idempotency_key:`complete-${q.id}`})});const d=await r.json();if(!r.ok){setError(d.error||"Answer could not be saved");return;}if(current<questions.length-1)await beginQuestion(current+1);else await finishInterview();}
 async function finishRecording(){const recorder=recorderRef.current;if(recorder&&recorder.state!=="inactive"){await new Promise<void>(resolve=>{recorder.addEventListener("stop",()=>resolve(),{once:true});recorder.stop();});}await uploadChain.current;setRecording(false);if(interview?.recording_enabled&&uploadIdRef.current){await fetch("/api/ai-interview/recording/finalize",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({upload_id:uploadIdRef.current,mime_type:recorder?.mimeType||"video/webm",duration_seconds:Math.round((Date.now()-startedAt.current)/1000)})});}}
 async function finishInterview(){if(step==="thanks")return;setStep("thanks");try{await finishRecording();await fetch("/api/ai-interview/complete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idempotency_key:`complete-${interview?.id}`})});mediaRef.current?.getTracks().forEach(t=>t.stop());screenRef.current?.getTracks().forEach(t=>t.stop());if(document.fullscreenElement)await document.exitFullscreen().catch(()=>{});}catch{setWarning("Your answers were submitted. Recording processing may require recruiter review.");}}
 const card="rounded-2xl border border-slate-700/70 bg-slate-900/80 p-5 shadow-xl shadow-black/10";
 if(step==="loading")return <Shell><div className={`${card} text-center text-slate-300`}>Opening your secure interview...</div></Shell>;
 if(step==="error")return <Shell><div className={`${card} text-center`}><h1 className="text-xl font-bold text-white">Unable to open interview</h1><p className="mt-3 text-slate-300">{error}</p></div></Shell>;
 if(step==="thanks")return <Shell><div className={`${card} text-center`}><CheckCircle2 className="mx-auto h-14 w-14 text-emerald-400"/><h1 className="mt-4 text-2xl font-bold text-white">Interview submitted successfully</h1><p className="mx-auto mt-3 max-w-xl text-slate-300">Thank you for completing the interview. Our recruitment team will review your responses and get back to you.</p>{warning&&<p className="mt-3 text-sm text-amber-300">{warning}</p>}</div></Shell>;
 if(step==="intro")return <Shell><div className={`${card} mx-auto max-w-3xl`}><div className="flex items-start gap-3"><ShieldCheck className="mt-1 h-7 w-7 text-cyan-400"/><div><h1 className="text-2xl font-bold text-white">{interview?.title}</h1><p className="mt-1 text-slate-300">{interview?.candidate_name} · {interview?.job_title} · {interview?.duration_minutes} minutes</p></div></div><p className="mt-5 whitespace-pre-wrap text-sm leading-6 text-slate-300">{interview?.instructions}</p><div className="mt-5 rounded-xl border border-slate-700 bg-slate-950/60 p-4 text-sm leading-6 text-slate-300">This interview uses your camera and microphone and may record audio/video. It monitors interview-tab visibility, focus, fullscreen, media interruptions, network state, face presence, and approximate head direction. These integrity signals are approximate and receive human review. No emotion or background-application detection is performed.</div><label className="mt-5 flex items-start gap-3 text-sm text-slate-200"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-1"/><span>I consent to the required camera, microphone, recording, and browser integrity monitoring described above.</span></label>{error&&<p className="mt-3 text-sm text-rose-300">{error}</p>}<button disabled={!consent||checking} onClick={()=>void acceptConsent()} className="mt-5 w-full rounded-xl bg-cyan-500 px-5 py-3 font-bold text-slate-950 disabled:opacity-40">Continue to system check</button></div></Shell>;
 if(step==="system")return <Shell><div className="mx-auto grid max-w-5xl gap-5 lg:grid-cols-2"><div className={card}><h1 className="text-xl font-bold text-white">Camera and microphone check</h1><video ref={videoRef} muted playsInline className="mt-4 aspect-video w-full rounded-xl bg-black object-cover"/><div className="mt-4 flex gap-2"><button onClick={()=>void runChecks()} disabled={checking} className="flex-1 rounded-xl bg-cyan-500 px-4 py-2.5 font-bold text-slate-950">{checking?"Checking...":"Run system check"}</button><button onClick={playSpeakerTest} className="rounded-xl border border-slate-600 px-4 py-2.5 text-sm font-semibold text-white">Test speaker</button></div>{error&&<p className="mt-3 text-sm text-rose-300">{error}</p>}</div><div className={card}><h2 className="text-xl font-bold text-white">System readiness</h2><div className="mt-4 space-y-3">{[["browser","Chrome or Edge",MonitorUp],["camera","Camera",Camera],["microphone","Microphone",Mic],["speaker","Speaker",Mic],["network","Network",Wifi],...(interview?.screen_share_enabled?[["screen","Screen share",MonitorUp] as any]:[])].map(([key,label,Icon]:any)=><div key={key} className="flex items-center justify-between rounded-xl border border-slate-700 p-3"><span className="flex items-center gap-2 text-slate-200"><Icon className="h-4 w-4"/>{label}</span><span className={checks[key]?"text-emerald-400":"text-slate-500"}>{checks[key]?"Ready":"Pending"}</span></div>)}</div><button onClick={()=>void beginInterview()} disabled={!Object.values(checks).every(Boolean)} className="mt-5 w-full rounded-xl bg-emerald-500 px-4 py-3 font-bold text-slate-950 disabled:opacity-40">Start interview</button></div></div></Shell>;
 const q=questions[current];return <Shell><div className="grid gap-5 lg:grid-cols-[1fr_320px]"><main className={card}><div className="flex flex-wrap items-center justify-between gap-3 text-sm text-slate-300"><span>Question {current+1} of {questions.length}</span><span className="flex items-center gap-2"><Clock className="h-4 w-4"/>{Math.floor(timeLeft/60)}:{String(timeLeft%60).padStart(2,"0")}</span></div><div className="mt-3 h-2 rounded-full bg-slate-800"><div className="h-full rounded-full bg-cyan-400" style={{width:`${((current+1)/Math.max(1,questions.length))*100}%`}}/></div><div className="mt-6 text-xs font-bold uppercase tracking-[.18em] text-cyan-400">{q?.skill_name||"Interview"} · {q?.difficulty}</div><h1 className="mt-3 text-2xl font-bold leading-9 text-white">{q?.question_text}</h1><button onClick={speakQuestion} disabled={speaking} className="mt-3 text-sm font-semibold text-cyan-300">{speaking?"Reading question...":"Read question aloud"}</button><textarea value={answer} onChange={e=>setAnswer(e.target.value)} rows={9} className="mt-6 w-full rounded-xl border border-slate-700 bg-slate-950/70 p-4 text-slate-100 outline-none focus:border-cyan-400" placeholder="Speak or type your answer here..."/><div className="mt-3 flex flex-wrap justify-between gap-2"><button onClick={startDictation} className="rounded-xl border border-slate-600 px-4 py-2 text-sm font-semibold text-white">Start voice transcription</button><button onClick={()=>void submitAnswer()} className="rounded-xl bg-cyan-500 px-5 py-2.5 font-bold text-slate-950">{current===questions.length-1?"Submit interview":"Save and next"}</button></div>{error&&<p className="mt-3 text-sm text-rose-300">{error}</p>}</main><aside className={card}><video ref={videoRef} muted autoPlay playsInline className="aspect-video w-full rounded-xl bg-black object-cover"/><div className="mt-4 space-y-2 text-sm text-slate-300"><div className="flex justify-between"><span>Camera</span><strong className="text-emerald-400">On</strong></div><div className="flex justify-between"><span>Microphone</span><strong className="text-emerald-400">On</strong></div><div className="flex justify-between"><span>Recording</span><strong className={recording?"text-rose-400":"text-slate-500"}>{recording?"Active":"Off"}</strong></div><div className="flex justify-between"><span>Network</span><strong className="text-emerald-400">Online</strong></div></div>{warning&&<div className="mt-4 rounded-xl border border-amber-500/40 bg-amber-500/10 p-3 text-sm text-amber-200">{warning}<button onClick={()=>setWarning("")} className="mt-2 block font-bold">Dismiss</button></div>}<p className="mt-4 text-xs leading-5 text-slate-500">Face and head-direction checks are approximate and are reviewed by a person.</p></aside></div></Shell>;
}

function Shell({children}:{children:React.ReactNode}){return <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,_#172554,_#020617_48%,_#020617)] px-4 py-8 text-white sm:px-6"><div className="mx-auto max-w-7xl"><div className="mb-7 flex items-center gap-3"><div className="rounded-xl bg-cyan-400 p-2 text-slate-950"><BrainCircuit className="h-6 w-6"/></div><div><div className="font-bold">AASTHIX AI Interview</div><div className="text-xs text-slate-400">Secure candidate assessment</div></div></div>{children}</div></main>}
